const mongoose = require("mongoose");
const Product = require("./models/Product");
require("dotenv").config();

const products = [
  {
    name: "iPhone 13",
    price: 49999,
    description: "Powerful smartphone with an advanced camera system and fast performance.",
    stock: 20,
    image: "https://cdn.dummyjson.com/product-images/smartphones/iphone-13/1.webp",
    category: "Smartphones",
    brand: "Apple",
    rating: 4.7,
    discountPercentage: 12,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "APL-IP13-001",
  },
  {
    name: "Samsung Galaxy S21",
    price: 44999,
    description: "Premium Samsung smartphone with a beautiful AMOLED display.",
    stock: 25,
    image: "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s21/1.webp",
    category: "Smartphones",
    brand: "Samsung",
    rating: 4.6,
    discountPercentage: 15,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "SAM-S21-002",
  },
  {
    name: "Samsung Galaxy S10",
    price: 34999,
    description: "Reliable smartphone with an excellent display and camera.",
    stock: 18,
    image: "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/1.webp",
    category: "Smartphones",
    brand: "Samsung",
    rating: 4.4,
    discountPercentage: 18,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "SAM-S10-003",
  },
  {
    name: "iPhone X",
    price: 29999,
    description: "Premium smartphone with a high-quality display and powerful processor.",
    stock: 15,
    image: "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/1.webp",
    category: "Smartphones",
    brand: "Apple",
    rating: 4.3,
    discountPercentage: 20,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "APL-IPX-004",
  },
  {
    name: "Vivo V23 5G",
    price: 27999,
    description: "Stylish 5G smartphone with a high-quality camera system.",
    stock: 30,
    image: "https://cdn.dummyjson.com/product-images/smartphones/vivo-v23-5g/1.webp",
    category: "Smartphones",
    brand: "Vivo",
    rating: 4.2,
    discountPercentage: 10,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "VIV-V23-005",
  },

  {
    name: "MacBook Pro 14",
    price: 129999,
    description: "Powerful professional laptop with excellent performance and display.",
    stock: 10,
    image: "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp",
    category: "Laptops",
    brand: "Apple",
    rating: 4.9,
    discountPercentage: 8,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "APL-MBP-006",
  },
  {
    name: "ASUS ROG Strix G15",
    price: 99999,
    description: "High-performance gaming laptop built for demanding games and applications.",
    stock: 12,
    image: "https://cdn.dummyjson.com/product-images/laptops/asus-rog-strix-g15/1.webp",
    category: "Laptops",
    brand: "ASUS",
    rating: 4.8,
    discountPercentage: 12,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "ASU-ROG-007",
  },
  {
    name: "Huawei MateBook X Pro",
    price: 89999,
    description: "Slim premium laptop designed for productivity and entertainment.",
    stock: 14,
    image: "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/1.webp",
    category: "Laptops",
    brand: "Huawei",
    rating: 4.5,
    discountPercentage: 14,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "HUA-MBP-008",
  },
  {
    name: "Lenovo Yoga 920",
    price: 74999,
    description: "Convertible laptop with a stylish design and flexible touchscreen.",
    stock: 16,
    image: "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/1.webp",
    category: "Laptops",
    brand: "Lenovo",
    rating: 4.4,
    discountPercentage: 16,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "LEN-YOG-009",
  },
  {
    name: "MacBook Pro M2 Max",
    price: 139999,
    description: "Advanced MacBook with powerful performance for professional workloads.",
    stock: 8,
    image: "https://cdn.dummyjson.com/product-images/laptops/macbook-pro-14-inch-m2-max/1.webp",
    category: "Laptops",
    brand: "Apple",
    rating: 4.9,
    discountPercentage: 7,
    availabilityStatus: "Low Stock",
    minimumOrderQuantity: 1,
    sku: "APL-M2M-010",
  },

  {
    name: "Essence Mascara Lash Princess",
    price: 499,
    description: "Volumizing mascara for beautiful and defined lashes.",
    stock: 30,
    image: "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp",
    category: "Beauty",
    brand: "Essence",
    rating: 4.6,
    discountPercentage: 10,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "ESS-MAS-011",
  },
  {
    name: "Eyeshadow Palette",
    price: 899,
    description: "Beautiful eyeshadow palette with multiple shades and a mirror.",
    stock: 25,
    image: "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp",
    category: "Beauty",
    brand: "BeautyPro",
    rating: 4.5,
    discountPercentage: 15,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "BEA-EYE-012",
  },
  {
    name: "Red Lipstick",
    price: 399,
    description: "Long-lasting lipstick with a smooth and attractive finish.",
    stock: 40,
    image: "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp",
    category: "Beauty",
    brand: "L'Oreal",
    rating: 4.7,
    discountPercentage: 12,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "LOR-LIP-013",
  },
  {
    name: "Red Nail Polish",
    price: 299,
    description: "Glossy nail polish with rich color and long-lasting finish.",
    stock: 45,
    image: "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp",
    category: "Beauty",
    brand: "ColorBar",
    rating: 4.3,
    discountPercentage: 20,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "COL-NLP-014",
  },
  {
    name: "Powder Canister",
    price: 699,
    description: "Compact powder product suitable for everyday makeup.",
    stock: 35,
    image: "https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp",
    category: "Beauty",
    brand: "Maybelline",
    rating: 4.4,
    discountPercentage: 13,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "MAY-PWD-015",
  },

  {
    name: "Calvin Klein CK One",
    price: 2499,
    description: "Classic fragrance with a fresh and elegant scent.",
    stock: 20,
    image: "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp",
    category: "Fragrances",
    brand: "Calvin Klein",
    rating: 4.7,
    discountPercentage: 10,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "CK-ONE-016",
  },
  {
    name: "Chanel Coco Noir",
    price: 5999,
    description: "Premium fragrance with a sophisticated and luxurious aroma.",
    stock: 15,
    image: "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp",
    category: "Fragrances",
    brand: "Chanel",
    rating: 4.9,
    discountPercentage: 8,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "CHA-CNO-017",
  },
  {
    name: "Dior J'adore",
    price: 4999,
    description: "Elegant floral fragrance suitable for special occasions.",
    stock: 18,
    image: "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
    category: "Fragrances",
    brand: "Dior",
    rating: 4.8,
    discountPercentage: 12,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "DIO-JAD-018",
  },
  {
    name: "Gucci Bloom",
    price: 4499,
    description: "Luxury floral fragrance with a modern and beautiful scent.",
    stock: 17,
    image: "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp",
    category: "Fragrances",
    brand: "Gucci",
    rating: 4.6,
    discountPercentage: 15,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "GUC-BLM-019",
  },
  {
    name: "Dolce Shine",
    price: 3299,
    description: "Fresh and bright fragrance for everyday use.",
    stock: 22,
    image: "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp",
    category: "Fragrances",
    brand: "Dolce & Gabbana",
    rating: 4.5,
    discountPercentage: 18,
    availabilityStatus: "In Stock",
    minimumOrderQuantity: 1,
    sku: "DOL-SHN-020",
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("MongoDB connected");

    await Product.deleteMany();

    await Product.insertMany(products);

    console.log(`${products.length} products inserted successfully`);

    mongoose.connection.close();
  })
  .catch((error) => {
    console.error("Database error:", error);
  });